# AerE 361 Mission action
# LaTeX compiler and checker
# Professor Nelson
name: Autograding
on: [push]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Check that they created the markdown file
      - name: Check for Markdown and History files
        id: check_markdown
      # You may pin to the exact commit or the version.
      # uses: andstor/file-existence-action@87d74d4732ddb824259d80c8a508c0124bf1c673
        uses: andstor/file-existence-action@v1.1.0
        with:
          # Comma separated string with paths to files and directories to check for existence.
          files: apd.md, history.txt
          allow_failure: true
      - name: File checker
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo Markdown and Hisory file is present!
# Runs the autograder test
      - uses: education/autograding@v1
